# Generated by Django 2.0 on 2018-10-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAndAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('body', models.TextField(verbose_name='文章')),
                ('author', models.CharField(default='sing', max_length=50, verbose_name='作者')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '首页和关于的页面内容',
                'verbose_name_plural': '首页和关于的页面内容',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='MySiteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.CharField(max_length=50, verbose_name='网站logo')),
                ('introduction', models.TextField(verbose_name='网站简介')),
                ('approval_number', models.CharField(default='暂无审批号', max_length=64, verbose_name='网站审批号')),
            ],
            options={
                'verbose_name': '网站信息',
                'verbose_name_plural': '网站信息',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ToolLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='链接文本')),
                ('link', models.CharField(help_text='请填写http或https开头的完整形式地址', max_length=200, verbose_name='链接')),
                ('img_link', models.URLField(help_text='请填写http或https开头的完整形式地址', null=True, verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '个人空间',
                'verbose_name_plural': '个人空间',
                'ordering': ['-id'],
            },
        ),
    ]
