# Generated by Django 2.0 on 2018-10-04 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toollinks',
            name='img_link',
            field=models.URLField(blank=True, default=django.utils.timezone.now, help_text='请填写http或https开头的完整形式地址', verbose_name='图片地址'),
            preserve_default=False,
        ),
    ]
